dist: bionic
language: ruby
script:
  - bundle exec rake db:structure:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - psql -c 'create database dgidb_test;'
rvm:
  - "2.6.5"
env:
  global:
    - RAILS_ENV=test TRAVIS_BUILD=true
    - PGVER=12
    - PGPORT=5433
    - PGHOST=''
notifications:
  email: false
git:
    submodules: false
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
